CONN / AS SYSDBA
--DROP USER rs CASCADE;
CREATE USER rs IDENTIFIED BY rs;
GRANT CONNECT TO rs;
GRANT RESOURCE TO rs;
GRANT CREATE VIEW TO rs;
GRANT CREATE ANY DIRECTORY TO rs;
GRANT CREATE PROCEDURE TO rs;
